import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { Box, Divider, SlideFade, VStack } from '@chakra-ui/react'
import { SideHeader } from '@/components/side-header'
import { FadeContainer } from '@/components/container'
import { NavList } from '@/components/items-display/navList'
import { GoUpIconButton } from '@/components/buttons/goUpIconButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nicolas Antunes | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const navTitles = [
    { title: 'á propos', href: '#about' },
    { title: 'projets', href: '#projects' },
    { title: 'parcours', href: '#resume' },
  ]

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <FadeContainer>
            <Box
              id="home"
              flex={{ base: 'auto', lg: '1' }}
              overflow="hidden"
              mt="5vh">
              <SlideFade
                in={true}
                transition={{
                  enter: { duration: '1.5', ease: 'easeOut' },
                }}
                offsetY="10vh">
                <SideHeader />
              </SlideFade>
            </Box>
            <VStack flex="2">
              <NavList links={navTitles} />
              <Divider sx={{ borderColor: 'var(--foreground) !important' }} />
              <Box
                id="main-content"
                flex="3"
                h={{ base: 'auto', lg: '90vh' }}
                p="1.5em"
                overflowY={{ base: 'unset', lg: 'auto' }}
                overflowX={{ base: 'unset', lg: 'hidden' }}
                sx={{
                  maskImage: `linear-gradient(
                      to bottom,
                      black calc(100% - 48px),
                      transparent 100%
                    )`,
                }}>
                {children}
              </Box>
              <Box display={{ lg: 'none' }} position="fixed" bottom='5' right='1.5'>
                <GoUpIconButton />
              </Box>
            </VStack>
          </FadeContainer>
        </Providers>
      </body>
    </html>
  )
}
