import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import {
  Box,
  Container,
  Flex,
  ScaleFade,
  SlideFade,
  VStack,
} from '@chakra-ui/react'
import { Header } from '@/app/header'
import { FadeContainer } from '@/components/fadeContainer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Container
            maxW="75vw"
            minH="100vh"
            p="1em"
            color="whitesmoke"
            opacity={'.9'}>
            <FadeContainer>
              <Box flex="2" overflow="hidden">
                <SlideFade
                  in={true}
                  transition={{
                    enter: { duration: '1.5', ease: 'easeOut' },
                  }}
                  offsetY="10vh">
                  <Header />
                </SlideFade>
              </Box>
              <Box
                id="main-content"
                flex="3"
                h="90vh"
                p="1.5em"
                overflowY="auto"
                overflowX="hidden"
                sx={{
                  'mask-image':
                    'linear-gradient(to bottom, black calc(100% - 48px), transparent 100%)',
                }}>
                {children}
              </Box>
            </FadeContainer>
          </Container>
        </Providers>
      </body>
    </html>
  )
}
