import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { Box, Container, Divider, SlideFade, VStack } from '@chakra-ui/react'
import { SideHeader } from '@/components/side-header'
import { FadeContainer } from '@/components/container'
import { NavList } from '@/components/items-display/navList'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nicolas Antunes | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const navTitles = [
    { title: 'about', href: '#about' },
    { title: 'projects', href: '#projects' },
    { title: 'resume', href: '#resume' },
  ]

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Container
            maxW="75vw"
            minH="100vh"
            p="1em"
            color="whitesmoke"
            opacity={'.9'}>
            <FadeContainer>
              <Box flex="2" overflow="hidden" mt='5vh'>
                <SlideFade
                  in={true}
                  transition={{
                    enter: { duration: '1.5', ease: 'easeOut' },
                  }}
                  offsetY="10vh">
                  <SideHeader />
                </SlideFade>
              </Box>
              <VStack flex="3">
                <NavList links={navTitles} />
                <Divider
                  sx={{ 'border-color': 'var(--foreground) !important' }}
                />
                <Box
                  id="main-content"
                  flex="3"
                  h="90vh"
                  p="1.5em"
                  overflowY="auto"
                  overflowX="hidden"
                  sx={{
                    'mask-image': `linear-gradient(
                        to bottom,
                        black calc(100% - 48px),
                        transparent 100%
                      )`,
                  }}>
                  {children}
                </Box>
              </VStack>
            </FadeContainer>
          </Container>
        </Providers>
      </body>
    </html>
  )
}
